import XCTest
@testable import LineDrawCore
final class CoreTests:XCTestCase{
    let html="""
    <div id="page-draws"><div class="draw-store" data-draw-city="台北市"><h2 class="draw-store-name">測試店</h2><div class="draw-start">抽選／購買時間：2026/09/28（一）10:00～2026/09/29（二）23:59</div><div class="draw-item" data-draw-id="one" data-draw-href="https://lin.ee/abc"><span class="draw-product">商品 A</span></div><div class="draw-item" data-draw-id="two" data-draw-href="https://liff.line.me/test/c/two"><span class="draw-product">商品 B</span></div></div></div>
    """
    func database()throws->LocalDatabase{let d=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString);addTeardownBlock{try? FileManager.default.removeItem(at:d)};return try LocalDatabase(file:d.appendingPathComponent("state.json"))}
    func testSourceOrderIdentityAndChinese()throws{let rows=try CatalogParser.parse(html);XCTAssertEqual(rows.map(\.product),["商品 A","商品 B"]);XCTAssertEqual(rows[1].activityKey,"coupon:test:two");XCTAssertNil(rows[0].canonicalURL);XCTAssertEqual(rows[0].city,"台北市")}
    func testTaipeiTenOClockIsTwoUTC()throws{let period=try DrawSchedule.parse("抽選／購買時間：2026/09/28（一）10:00～2026/09/29（二）23:59");XCTAssertEqual(period.0,WireJSON.parseDate("2026-09-28T02:00:00Z"));XCTAssertEqual(period.1,WireJSON.parseDate("2026-09-29T15:59:00Z"))}
    func testSeparateCouponUsageDoesNotSupplyDrawDeadline()throws{let period=try DrawSchedule.parse("抽選：2026/09/28 10:00｜使用期限：2026/09/29 23:59");XCTAssertNotNil(period.0);XCTAssertNil(period.1)}
    func testMalformedDateIsUnknown()throws{let p=try DrawSchedule.parse("抽選：2026/02/30 10:00～2026/03/03 23:59");XCTAssertNil(p.0)}
    func testConflictingRangeRejected(){XCTAssertThrowsError(try DrawSchedule.parse("抽選：2026/09/29 10:00～2026/09/28 23:59"))}
    func testMissingRowsAndDuplicateIDsRejectWholePage(){XCTAssertThrowsError(try CatalogParser.parse("<html>login</html>"));XCTAssertThrowsError(try CatalogParser.parse(html.replacingOccurrences(of:"data-draw-id=\"two\"",with:"data-draw-id=\"one\"")));XCTAssertThrowsError(try CatalogParser.parse(html.replacingOccurrences(of:"data-draw-href=\"https://lin.ee/abc\"",with:"")))}
    func testExternalAndCredentialLinksRejected(){XCTAssertFalse(LinkPolicy.allowed("https://lin.ee.evil.test/abc"));XCTAssertFalse(LinkPolicy.allowed("https://user@lin.ee/abc"));XCTAssertNil(LinkPolicy.canonical("https://liff.line.me/test/c/id?next=evil"));XCTAssertFalse(LinkPolicy.allowed("http://lin.ee/abc"))}
    func testEligibilityBoundaryAndUnresolved()throws{let rows=try CatalogParser.parse(html);let start=rows[1].startsAt!;let end=rows[1].endsAt!;XCTAssertEqual(rows[1].eligibility(at:start),.ready);XCTAssertEqual(rows[1].eligibility(at:end),.expired);XCTAssertEqual(rows[1].eligibility(at:start.addingTimeInterval(-1)),.notStarted);XCTAssertFalse(rows[0].runnable(at:start))}
    func testFilterORWithinANDbetween(){let rows=TestCatalog.demo();var f=CatalogFilter();f.cities=["台北市","台中市"];f.statuses=[.ready,.notStarted];XCTAssertTrue(f.matches(rows[0],recorded:false));XCTAssertTrue(f.matches(rows[3],recorded:false));f.query="幻影";XCTAssertFalse(f.matches(rows[3],recorded:false));XCTAssertTrue(f.matches(rows[1],recorded:false));XCTAssertFalse(f.matches(rows[1],recorded:true))}
    func testAllExcludesArchived(){var row=TestCatalog.demo()[0];row.archived=true;var f=CatalogFilter();XCTAssertFalse(f.matches(row,recorded:false));f.statuses=[.archived];XCTAssertTrue(f.matches(row,recorded:false))}
    func testSyncArchivesAndPreservesRecords()throws{var db=try database();let rows=TestCatalog.demo();try db.merge(rows,area:.demo);try db.manual(rows[0],profile:"default");try db.merge(Array(rows.dropFirst()),area:.demo);XCTAssertTrue(db.snapshot.draws.first{$0.id==rows[0].id}!.archived);XCTAssertEqual(db.records(profile:"default",area:.demo)[rows[0].activityKey]?.status,"MANUAL")}
    func testInvalidMergeRetainsLastSnapshot()throws{var db=try database();try db.merge(TestCatalog.demo(),area:.demo);let before=db.snapshot.draws;XCTAssertThrowsError(try db.merge([],area:.demo));XCTAssertEqual(db.snapshot.draws,before)}
    func testUndoRestoresSubmittedInsteadOfClearing()throws{var db=try database();let row=TestCatalog.demo()[0];let r=ParticipationRecord(id:row.activityKey,product:row.product,store:row.store,status:"SUBMITTED",evidence:"original");try db.importRecords([r],profile:"p",area:.demo);try db.manual(row,profile:"p");try db.undo(activityKey:row.activityKey,profile:"p",area:.demo);XCTAssertEqual(db.records(profile:"p",area:.demo)[row.activityKey],r)}
    func testUndoNewManualReturnsUnrecorded()throws{var db=try database();let row=TestCatalog.five()[0];try db.manual(row,profile:"p");try db.undo(activityKey:row.activityKey,profile:"p",area:.test);XCTAssertNil(db.records(profile:"p",area:.test)[row.activityKey]);XCTAssertEqual(db.snapshot.bridgeOutbox.map(\.action),["manual","undo"])}
    func testRecordsAreProfileAndAreaScoped()throws{var db=try database();let row=TestCatalog.demo()[0];try db.manual(row,profile:"a");XCTAssertTrue(db.records(profile:"b",area:.demo).isEmpty);XCTAssertTrue(db.records(profile:"a",area:.website).isEmpty)}
    func testStaleCompanionPollCannotUndoLocalManual()throws{var db=try database();let row=TestCatalog.five()[0];try db.manual(row,profile:"p");try db.importRecords([ParticipationRecord(id:row.activityKey,product:"x",store:"x",status:"SUBMITTED",evidence:"stale")],profile:"p",area:.test);XCTAssertEqual(db.records(profile:"p",area:.test)[row.activityKey]?.status,"MANUAL")}
    func testDurableManualUndoAndConsent()throws{var db=try database();let row=TestCatalog.demo()[0];try db.manual(row,profile:"a");try db.update{$0.consentVersion=UsageDeclaration.version};var reopened=try LocalDatabase(file:db.file);XCTAssertEqual(reopened.snapshot.consentVersion,UsageDeclaration.version);try reopened.undo(activityKey:row.activityKey,profile:"a",area:.demo);XCTAssertNil(reopened.records(profile:"a",area:.demo)[row.activityKey])}
    func testPairingRequiresLocalHTTPSExactFields(){let fingerprint=String(repeating:"a",count:64);XCTAssertNoThrow(try PairingInvitation(raw:"linedraw://pair?endpoint=https%3A%2F%2F192.168.1.2%3A4781&fingerprint=\(fingerprint)&code=123456"));XCTAssertThrowsError(try PairingInvitation(raw:"linedraw://pair?endpoint=https%3A%2F%2Fevil.com%3A4781&fingerprint=\(fingerprint)&code=123456"));XCTAssertThrowsError(try PairingInvitation(raw:"linedraw://pair?endpoint=http%3A%2F%2F192.168.1.2%3A4781&fingerprint=\(fingerprint)&code=123456"));XCTAssertThrowsError(try PairingInvitation(raw:"linedraw://pair?endpoint=https%3A%2F%2F192.168.1.2%3A4781&fingerprint=\(fingerprint)&code=123456&code=987654"))}
    func testWireDatesAcceptMillisecondsAndSeconds()throws{XCTAssertNotNil(WireJSON.parseDate("2026-09-28T13:28:04.089Z"));XCTAssertNotNil(WireJSON.parseDate("2026-09-28T13:28:04Z"));let rows=TestCatalog.five();XCTAssertEqual(try WireJSON.decoder().decode([Draw].self,from:WireJSON.encoder().encode(rows)),rows)}
    func testCorruptStorageNeverOverwritten()throws{let d=try database();try FileManager.default.createDirectory(at:d.file.deletingLastPathComponent(),withIntermediateDirectories:true);let raw=Data("invalid".utf8);try raw.write(to:d.file);XCTAssertThrowsError(try LocalDatabase(file:d.file));XCTAssertEqual(try Data(contentsOf:d.file),raw)}
    func testDiagnosticExpiryAndNoActivityFields()throws{var db=try database();try db.log("OLD","old",now:Date().addingTimeInterval(-31*86400));try db.log("SYNC","同步完成");XCTAssertEqual(db.snapshot.diagnostics.count,1);XCTAssertFalse(db.diagnosticsText().contains("https://"))}
    func testTransientResolutionFailurePreservesIdentityAndHistory()throws{var db=try database();let row=TestCatalog.five()[0];try db.merge([row],area:.test);try db.manual(row,profile:"p");var unresolved=row;unresolved.canonicalURL=nil;unresolved.activityKey=LinkPolicy.key(row.url);try db.merge([unresolved],area:.test);XCTAssertEqual(db.snapshot.draws[0].activityKey,row.activityKey);XCTAssertEqual(db.snapshot.draws[0].canonicalURL,row.canonicalURL);XCTAssertEqual(db.records(profile:"p",area:.test)[db.snapshot.draws[0].activityKey]?.status,"MANUAL")}

}
