import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../src/store.mjs';import {PairingGate} from '../src/pairing.mjs';import {MobileController} from '../src/mobile-controller.mjs';import {parseWebsite,schedule,resolveLink,continuationRows} from '../src/mobile-catalog.mjs';import {page} from './helpers.mjs';
const pair={identity:'paired-device',udid:'simulator-only'};
function setup(t,options={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'linedraw-mobile-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const store=new Store(directory);let clock=0,taps=0;const driver={sessionId:'fake',udid:pair.udid,open:async()=> 'old',snapshot:async()=>page(['抽選']),tap:async()=>{taps++;}};const controller=new MobileController({store,getDriver:()=>driver,online:async()=>true,engineOptions:{clock:()=>clock,delay:async ms=>{clock+=ms;},pollMs:1,settleMs:0},...options});return {store,driver,controller,taps:()=>taps};}
function row(n){return{id:'row'+n,activityKey:'coupon:app:coupon'+n,store:'測試店',city:n%2?'台北市':'台中市',product:'商品'+n,url:'https://liff.line.me/app/c/coupon'+n,canonicalURL:'https://liff.line.me/app/c/coupon'+n,timeLabel:'',startsAt:'2020-01-01T00:00:00Z',endsAt:'2099-01-01T00:00:00Z',ordinal:n,area:'website',archived:false};}
function body(rows=[row(1)]){return{requestID:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',profile:'預設',area:'website',accepted:true,rows,selectedIDs:[rows[0].id],records:[],filter:{cities:[],statuses:[],query:''},autoFriend:true,autoContinue:false};}
test('pair code is single use, expires, and five bad attempts disable it',t=>{const {store}=setup(t);let now=1;const gate=new PairingGate({store,now:()=>now});const invite=gate.invite('phone');const token=gate.pair(invite.code);assert.equal(gate.authorize('Bearer '+token).udid,'phone');assert.throws(()=>gate.pair(invite.code));assert(!JSON.stringify(store.data).includes(token));const bad=gate.invite('phone');for(let i=0;i<5;i++)assert.throws(()=>gate.pair(bad.code==='000000'?'999999':'000000'));assert.throws(()=>gate.pair(bad.code));const old=gate.invite('phone');now+=300001;assert.throws(()=>gate.pair(old.code));gate.revokeAll();assert.throws(()=>gate.authorize('Bearer '+token));});
test('native batch respects source order, deduplicates, and retries request id without resubmission',async t=>{const env=setup(t),rows=[row(1),row(2),{...row(1),id:'alias'}],b={...body(rows),selectedIDs:['row2','alias','row1']};env.controller.start(pair,b);env.controller.start(pair,b);await env.controller.worker;assert.equal(env.taps(),2);const result=env.controller.view(pair,b);assert.equal(result.engine.state,'COMPLETED');assert.deepEqual(result.engine.queue.map(x=>x.id),['coupon:app:coupon1','coupon:app:coupon2']);env.controller.start(pair,b);assert.equal(env.taps(),2);});
test('native API refuses unconsented, fake identity, wrong device, demo or malformed time',t=>{const env=setup(t);assert.throws(()=>env.controller.start(pair,{...body(),accepted:false}));assert.throws(()=>env.controller.start({...pair,udid:'another-device'},body()));assert.throws(()=>env.controller.start(pair,{...body(),area:'demo'}));assert.throws(()=>env.controller.start(pair,body([{...row(1),activityKey:'coupon:wrong:id'}])));assert.throws(()=>env.controller.start(pair,body([{...row(1),startsAt:'2026-09-28T10:00:00'}])));assert.equal(env.taps(),0);});
test('manual undo is durable, restores submitted evidence, and is idempotent',t=>{const {store,controller}=setup(t),context=controller.context(pair,{profile:'a',area:'test'});store.setRecord(context.scope,'coupon:app:coupon1','SUBMITTED','original');const mutation={id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',profile:'a',area:'test',activityKey:'coupon:app:coupon1',product:'x',store:'y',action:'manual'};controller.mutate(pair,[mutation]);controller.mutate(pair,[mutation]);assert.equal(store.record(context.scope,mutation.activityKey).status,'MANUAL');controller.mutate(pair,[{...mutation,id:'cccccccc-cccc-cccc-cccc-cccccccccccc',action:'undo'}]);assert.equal(store.record(context.scope,mutation.activityKey).status,'SUBMITTED');assert.equal(store.record(context.scope,mutation.activityKey).reason,'original');assert.equal(controller.view(pair,{profile:'b',area:'test'}).records.length,0);});
test('mutation validation failure commits nothing',t=>{const {store,controller}=setup(t);const before=JSON.stringify(store.data);assert.throws(()=>controller.mutate(pair,[{id:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',profile:'a',area:'test',activityKey:'coupon:app:id',action:'manual'},{}]));assert.equal(JSON.stringify(store.data),before);});
test('continuation excludes unselected old IDs, preserves filters and adds at most 3 rounds',async t=>{let calls=0;const env=setup(t,{fetchCatalog:async()=>[row(1),row(2),...Array.from({length:++calls},(_,i)=>row(i+3))]});const b={...body([row(1),row(2)]),autoContinue:true};env.controller.start(pair,b);await env.controller.worker;const s=env.controller.view(pair,b);assert.equal(calls,3);assert.equal(env.taps(),4);assert.equal(s.round,3);assert.deepEqual(s.engine.queue.map(r=>r.id),[1,3,4,5].map(n=>'coupon:app:coupon'+n));assert(!s.records.some(r=>r.id==='coupon:app:coupon2'));});
test('continuation filter uses multi-city OR and status AND, no requeue of failures',()=>{const rows=[row(1),row(2),row(3)];const result=continuationRows(rows,{seen:new Set([row(1).activityKey]),filter:{cities:['台北市','台中市'],statuses:['ready'],query:'商品'},record:id=>id===row(2).activityKey?{status:'LOAD_TIMEOUT'}:null});assert.deepEqual(result.map(r=>r.id),['row3']);});
test('test area never fetches website for continuation',async t=>{const env=setup(t,{fetchCatalog:async()=>{throw new Error('must not sync')}});const r={...row(1),area:'test'},b={...body([r]),area:'test',autoContinue:true};env.controller.start(pair,b);await env.controller.worker;assert.equal(env.controller.engine.state,'COMPLETED');assert.equal(env.taps(),1);});
test('unknown click failure remains REVIEW and cannot be resubmitted',async t=>{const env=setup(t);env.driver.tap=async()=>{throw new Error('transport interrupted')};env.controller.start(pair,body());await env.controller.worker;const s=env.controller.view(pair,body());assert.equal(s.engine.state,'PAUSED');assert.equal(s.records[0].status,'REVIEW');env.controller.control(pair,body(),'stop');assert.throws(()=>env.controller.start(pair,{...body(),requestID:'dddddddd-dddd-dddd-dddd-dddddddddddd'}));});
test('website parser preserves order and separates coupon-use deadline',()=>{const html='<section id="page-draws"><div class="draw-store" data-draw-city="台北市"><b class="draw-store-name">商家</b><div class="draw-start">抽選/購買時間：2026/09/28（一）10:00～2026/09/29（二）23:59</div><div class="draw-item" data-draw-id="a" data-draw-href="https://lin.ee/abc"><span class="draw-product">陀螺</span></div></div></section>';const rows=parseWebsite(html);assert.equal(rows[0].startsAt,'2026-09-28T02:00:00.000Z');assert.equal(rows[0].endsAt,'2026-09-29T15:59:00.000Z');assert.equal(rows[0].product,'陀螺');assert.deepEqual(schedule('抽選：2026/09/28 10:00｜使用期限：2026/09/29 23:59'),['2026-09-28T02:00:00.000Z',null]);assert.throws(()=>parseWebsite(html.replace('data-draw-id="a"','')));});
test('short-link redirect never follows an external host',async()=>{const calls=[];await assert.rejects(resolveLink('https://lin.ee/abc',async url=>{calls.push(url);return new Response('',{status:301,headers:{location:'https://evil.test/x'}});}));assert.deepEqual(calls,['https://lin.ee/abc']);});
test('stop aborts an in-flight continuation sync and unlocks the batch',async t=>{let entered;const started=new Promise(r=>entered=r);const env=setup(t,{fetchCatalog:signal=>new Promise((resolve,reject)=>{entered();signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true});})});env.controller.start(pair,{...body(),autoContinue:true});await started;env.controller.stop();await env.controller.worker;assert.equal(env.controller.locked,false);assert.equal(env.controller.engine.state,'STOPPED');assert.equal(env.taps(),1);});

test('展示販售列不會阻擋有效抽選，殘缺操作列仍拒絕',()=>{
 const sale='<div class="draw-item"><b class="draw-product">BX-37（採取上架販售）</b></div>';
 const draw='<div class="draw-item draw-item-clickable" data-draw-id="a" data-draw-href="https://lin.ee/a"><b class="draw-product">商品</b></div>';
 const html=rows=>'<section id="page-draws"><div class="draw-store"><b class="draw-store-name">店家</b>'+rows+'</div></section>';
 assert.equal(parseWebsite(html(sale+draw)).length,1);assert.throws(()=>parseWebsite(html(sale)));assert.throws(()=>parseWebsite(html(draw+sale.replace('class="draw-item"','class="draw-item" onclick="go()"'))));
});
test('陀螺獵人使用台北時間、獨立列識別及共用券識別',async()=>{
 const {parseHunter,fetchWebsite}=await import('../src/mobile-catalog.mjs');
 const r={id:1,line_url:'https://liff.line.me/app/c/coupon1',store_name:'測試店',city:'台北市',product_name:'商品',start_time:'2026-10-02 11:00:00',end_time:'2026-10-03 21:00:00'};
 const rows=parseHunter(JSON.stringify({draws:[r]}));assert.equal(rows[0].startsAt,'2026-10-02T03:00:00.000Z');assert.equal(rows[0].activityKey,'coupon:app:coupon1');assert(rows[0].id.startsWith('catalog:beybladehunter:'));
 assert.deepEqual(parseHunter('{"draws":[]}'),[]);assert.throws(()=>parseHunter('{}'));
 for(const change of [{id:true},{id:1.5},{id:'01'},{start_time:'2026-02-30 10:00:00'},{line_url:'https://evil.test/a'}])assert.throws(()=>parseHunter(JSON.stringify({draws:[{...r,...change}]})));
 const calls=[];await fetchWebsite(async url=>{calls.push(url);return new Response(JSON.stringify({draws:[r]}));},{source:'beybladehunter'});assert.deepEqual(calls,['https://beybladehunter.com/api/funbox/data']);
 await assert.rejects(fetchWebsite(()=>{throw new Error('不應連線');},{source:'__proto__'}));
});
test('Mac 自動接續固定使用開始批次時選擇的來源',async t=>{
 const calls=[];const env=setup(t,{fetchCatalog:async(signal,source)=>{calls.push(source);return[row(1)];}});
 const b={...body(),autoContinue:true,catalogSource:'beybladehunter'};
 env.controller.start(pair,b);await env.controller.worker;assert.deepEqual(calls,['beybladehunter']);assert.equal(env.taps(),1);assert.deepEqual(env.controller.view(pair,b).catalogSources,['funbox','beybladehunter']);
 assert.throws(()=>env.controller.start(pair,{...body(),catalogSource:'unknown'}));
});

test('陀螺獵人網路檢查使用 GET，避免 HEAD 404 誤判離線',async t=>{
 const calls=[];const env=setup(t,{probeFetch:async(url,options)=>{calls.push([url,options.method]);return new Response('{}',{status:200});}});
 env.controller.run={catalogSource:'beybladehunter'};assert.equal(await env.controller.probe(),true);
 assert.deepEqual(calls,[['https://beybladehunter.com/api/funbox/data','GET']]);
});
